options:
  tickTime:
    default: 2000
    type: int

  initLimit:
    default: 10
    type: int

  syncLimit:
    default: 5
    type: int

  dataDir:
    default: "/home/work/data"
    type: string

  logDir:
    default: "/home/work/log"
    type: string

  group:
    default: ""
    type: string
