name: zookeeper

requires:
  - name: up
    interface: peer

provides:
  - name: down
    interface: peer

ports:
  - client_port
  - communicate_port
  - election_port

bns:
  ports:
    main: client_port
