#!/bin/bash
set -eu

source $OSP_PROGRAM_HOME/scripts/common.sh

log_info "Check environment variables"
if ! check_unit_env; then
    log_fatal "Failed to check unit environment variables"
fi

log_info "Build"
if ! $OSP_PROGRAM_HOME/scripts/build $build_dir; then
    log_fatal "Failed to build service"
fi

log_info "Copy the executable"
cp $build_dir/zookeeper-3.4.6/* $OSP_UNIT_HOME/ -r

conf_file=$OSP_UNIT_HOME/conf/zoo.cfg
log_info "Create $conf_file"
touch $conf_file

data_dir=$OSP_UNIT_HOME/data
log_info "create $data_dir"
mkdir -p $data_dir
